### ISSUE TITLE
Lexical error appears when filtering marker names with regular expression

### ISSUE THREAD

**Issue by maijs** [FacilMap/facilmap2#101]
**Description**

When I enter regular expression (`name ~= "^[Cc]amp$"`) in the filter text area on a collaborative map, I get an error:
```
Lexical error on line 1. Unrecognized text.
name ~= "^[Cc]amp$"
-----^
```

**Steps to reproduce**

1. Have some markers on your collaborative map
2. Open `Tools` > `Filter`
3. Enter `name ~= "^[Cc]amp$`
4. See that lexical error appears

![image](https://user-images.githubusercontent.com/187887/47223347-b72b0980-d3c1-11e8-9a76-0f9ab6fcf9fc.png)

**Comment by cdauth** [comment]
Should work now.
