### ISSUE TITLE
facilmap.org website down

### ISSUE THREAD

**Issue by narcisgarcia** [FacilMap/facilmap2#104]
Today facilmap.org is not showing Facilmap contents.

**Comment by cczapp** [comment]
Yes, I am also getting 502 Bad Gateway error and unable to view contents. Please keep us posted on any updates. Thanks.

**Comment by cdauth** [comment]
Sorry, something crashed on the server, I restarted it now.

**Comment by cczapp** [comment]
Great, thanks @cdauth !
