### ISSUE TITLE
markers disappeared and GeoJSON file is empty

### ISSUE THREAD

**Issue by grago57** [FacilMap/facilmap2#110]
I just started using Facilmap. I created a map with a bunch of markers, exported as GeoJSON, and then almost immediately after found that all my markers had disappeared. I tried to open the GeoJSON file I'd just saved but found that it was only 1KB and apparently doesn't have any data. I'm pretty sure I didn't do anything between saving the GeoJSON file and finding that the markers had disappeared. Any ideas what might have happened and how to avoid it in the future? I'm using Firefox and Windows 10, in case that matters.

**Comment by cdauth** [comment]
Do you see anything in the map history?

How exactly did you create the markers? Using the "Add" → "Marker" menu?
