### ISSUE TITLE
Markers get duplicated if "cluster markers" is on when hidding/showing

### ISSUE THREAD

**Issue by eauchat** [FacilMap/facilmap2#117]
Just a small issue.
If "cluster markers" is on for a map and I click in the legend to show/hide a layer. Every time I click, it re-adds markers to the map display, so you end up having 10 time the same marker in the same place.
It's just a display issue, reloading the map resets it to the initial state.

**Comment by cdauth** [comment]
This is hopefully fixed in FacilMap 3. You can try out the beta version on [beta.facilmap.org](https://beta.facilmap.org/). Note that it is a temporary instance, any maps that you create or edit there will be removed at some point again. Please report any issues here on GitHub.

**Comment by eauchat** [comment]
Yep, tested in beta.facilmap.org, nice :)
