### ISSUE TITLE
Error in the search / route tracing bar

### ISSUE THREAD

**Issue by alexennis** [FacilMap/facilmap2#127]
When I try and search or trace directions from two destinations I get the following error code:

Error: connect ECONNREFUSED 130.117.76.9:443

What should I do to resolve? Please help

**Comment by cdauth** [comment]
Hm, I'm not sure, sometimes OpenRouteService has some temporary issues that get resolved again after a while.

If you check "Load route details" in the route options, it uses Mapbox instead of OpenRouteService, so maybe that works?

**Comment by alexennis** [comment]
Hi,

Tried that but it still doesn't work. Same error message

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by cdauth** [comment]
Ah, the problem is Nominatim, not OpenRouteService or Mapbox.

I'm not sure what the problem is, maybe a temporary outage.

All I can recommend you for now is to enter the coordinates as the start/destination, rather than the place name. You can find out the coordinates by hovering with the mouse over the place, the coordinates are written on the bottom right of the screen.

**Comment by alexennis** [comment]
I get the same error code even when I try to route between two sets of
coordinates...

Nothing else to recommend? Thanks

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by cdauth** [comment]
I have asked in the OSM community whether someone can help. Maybe the IP address of my server is somehow blocked from using the OSM search.

**Comment by cdauth** [comment]
It seems to work again. Eventually I will have to migrate to a different search provider, because it seems that my server was temporarily banned for exceeding the rate limit.
