### ISSUE TITLE
Finish collaborative map

### ISSUE THREAD

**Issue by narcisgarcia** [FacilMap/facilmap2#32]
Once I've "Started collaborative map", how to finish the session and be back again to clean facilmap?

**Comment by cdauth** [comment]
Interesting.

The manual way is obviously to remove the map ID from the URL.

I don’t have a good idea how to integrate this into the UI. Maybe a click on the FacilMap logo should just least back to the front page, so to a new clean map?

**Comment by narcisgarcia** [comment]
Yes, I reached this with the URL hack, but... any unexperienced user looking for a well-labeled button?

**Comment by RM87** [comment]
Maybe another entry in Tools menu named something like "Leave this map" above  "About" entry?
FacilMap logo is  an option too, but it could be  too easy to click on it by mistake.
