### ISSUE TITLE
Disable autozoom

### ISSUE THREAD

**Issue by narcisgarcia** [FacilMap/facilmap2#33]
Some way to disable the automatic move to general view of route while user is marking new points for a route?

**Comment by cdauth** [comment]
Which way of marking new points for a route do you mean?

**Comment by narcisgarcia** [comment]
Steps:
1. Open facilmap
2. set a start point for a route
3. set next point for the route and/or [Go]
<<View moves and zooms>>

The problem for the user can be when is setting detailed 3rd or 4th route points, and everytime view zooms out.

**Comment by cdauth** [comment]
I still don’t understand what exactly you are doing. In point 3 you are typing in a destination and then pick one from the dropdown list?

**Comment by narcisgarcia** [comment]
Do you mean not to know what move/zoom effect I'm talking about??

**Comment by cdauth** [comment]
I know the effect that you are talking about, but I’m trying to understand why it is disturbing you. There are multiple ways to add route points, which is why I’m trying to find out which one you are using.

**Comment by narcisgarcia** [comment]
1. Open facilmap.org
2. Introduce "Paris" at search box -> Use as: Route start -> Zooms&moves (good)
3. Introduce "rome italia" at next box -> No route draw&calculation? -> Press [Go]!
4. Manually zoom to Rome destination point, I want to add a (yellow) point to visit "Porta di Roma" before. Application adds the intermediate yellow mark and recalculates; Ok. Now there are 3 points at table widget.
5. Oh, i was wrong and remove [-] 2nd point to do it better: ZOOMS ALL OUT (bad) (route is back again Paris-Rome).
6. Now i [Add another destination] (cannot simply click on a map place) I write to new 3rd box "arco di travertino" and select the one in found list. ZOOMS ALL OUT (bad, I may want to add more detailed destinations!)

**Comment by cdauth** [comment]
Ok, I propose removing autozoom in the following situations:

* When loading the map and there is a route in the location hash (this should anyways not happen, this is a bug)
* When removing a route point by double-clicking on it or by removing it by clicking the minus in the routing form
* When adding a new route point via the “Use as” menu and a route is already drawn (by the way, you can do this by clicking on the map for more than 1 second)

I propose to keep autozoom in these situations:

* When pressing “Go!”
* When selecting a different route point suggestion in the route form
* When changing the route mode
* When adding a new route point via the “Use as” menu when no route is drawn yet

**Comment by narcisgarcia** [comment]
Corrections seem good, but a checkbox or icon to disable autozoom can help in these and more situations.

**Comment by narcisgarcia** [comment]
I see today that in facilmap.org the example with "arco di travertino" still fails.

**Comment by cdauth** [comment]
Personally, I think in that case it's justified. Usually, the suggestions are in different places of the world, so it makes sense to me that it zooms to the route when you select a different suggestion.

To avoid the zoom, you can long-click on the map and use the “Use as” menu.
