### ISSUE TITLE
Export user points

### ISSUE THREAD

**Issue by narcisgarcia** [FacilMap/facilmap2#36]
Feature request:
Additionally to allow exporting complete GPX, it could be useful to export&import a (different?) file with the only data user specified: start place and next places for a route.
This way will allow to load and continue a route design.

The file could be in same GPX file format (different extension?) but with only the track points the user introduced. If user only introduced a start point and a final point, the file can only contain those 2 points (as if the route was only a straight line).
When loading the file, facilmap could replay user's actions and allow "continue route editing session".

**Comment by narcisgarcia** [comment]
This may be related to issue #9 ?

**Comment by cdauth** [comment]
Yes, in the GPX format this is the difference between “track points” and “route points”.

Actually, the export functionality is already implemented, there is just no UI for it yet. The plan is to have a dialog coming up when exporting the map, where different settings like this one can be selected.

Importing such files is indeed meant by #9.

**Comment by narcisgarcia** [comment]
What is the current way to modify a saved or exported+imported route?

**Comment by cdauth** [comment]
There is currently no way.

**Comment by narcisgarcia** [comment]
Oh, I've just discovered that there is a way: The URL serves as import/export data.
Once the route is drawn, I just copy the current URL. If I want to continue work, I just paste that URL to webbrowser opens facilmap with last status.

**Comment by cdauth** [comment]
With commit 95c226305 (not yet installed on facilmap.org), it is now possible to access the GPX file through the URL `https://facilmap.org/<map ID>/gpx`. By appending `?useTracks=0` or `?useTracks=1` you can switch between exporting route points or track points.

**Comment by narcisgarcia** [comment]
Nice.
