### ISSUE TITLE
get direct link for a specific view

### ISSUE THREAD

**Issue by tremon89** [FacilMap/facilmap2#37]
I've discovered Facilmap just some hours ago and I already adore it! :-)

I would like to include my map in my website trough an iframe. So far - this works great.
But I would also like to load a specific view. Is there a direct hyperlink to a view?

e.g.: I created a view "standard" and another view "detail1". In my website I would like to include "detail1". It would be great to include it somehow like this: https://facilmap.org/mymap/detail1

Is this already possible or could you implement that?

**Comment by cdauth** [comment]
Hey,

at the moment this is not possible, but there is issue #14 for it.

For now, you can include the location hash in the URL. Go to your view, and the URL will become something like https://facilmap.org/mymap#x/y/z/abc. This link will always show the part of the map that you are currently viewing.

**Comment by cdauth** [comment]
I'm closing this as a duplicate, but feel free to ask more questions.
