### ISSUE TITLE
Feature request: Near self-contained and without more third parties

### ISSUE THREAD

**Issue by narcisgarcia** [FacilMap/facilmap2#49]
Current installation at facilmap.org uses stuff from thunderforest.com and uni-heidelberg.de , and this has 2 disadvantages:
1. Tracker blockers warn about this and block resource (map is shown anyway; I don't know the need)
2. This design makes users and sysadmins to distrust FacilMap.

**Comment by cdauth** [comment]
Which resources are you talking about? The map tiles? I see neither the possibility nor the necessity to self-host those.

**Comment by narcisgarcia** [comment]
I've tried facilmap.org with a web browser blocking thunderforest.com and uni-heidelberg.de , and map tiles are shown anyway. This means other kind of resources are taken from those domains (fonts? scripts? images? styles?)

**Comment by cdauth** [comment]
No, not really. As far as I can think, no non-image resources are taken from any other domains. Maybe your browser had the images cached?

**Comment by narcisgarcia** [comment]
May be the cache confusion. Now I've tried with new zones and cannot view tiles unless I set exceptions for those domains.
Thanks.
