### ISSUE TITLE
support leaflet.markercluster for big data

### ISSUE THREAD

**Issue by pmgouveia** [FacilMap/facilmap2#53]
yep... im using a script to import data to a facilmap... and kaboom it crashes..

it has 3.000 points only. markercluster is an easy option!

**Comment by cdauth** [comment]
Good idea, I didn’t know about it!

Would it be possible for you to share a link to a FacilMap that crashes? (For example the read-only link to your map)

**Comment by pmgouveia** [comment]
ei, i was trying to implement this but i didn't find a good way to debug the frontend. here is my first approach!
https://github.com/pmgouveia/facilmap2/tree/markercluster

**Comment by pmgouveia** [comment]
my map is localhost, i implemented a script to import a csv file... to a default pad! i only works for mysql because i was to lazy to check how to implement it with sequelize. 

https://github.com/pmgouveia/facilmap2/tree/oilmap/scripts

you can download the data from https://incidentnews.noaa.gov/raw/index

**Comment by pmgouveia** [comment]
I was able to run it now.. ! it was just about running `npm run build` before refreshing the browser...
preparing a pull request!

**Comment by cdauth** [comment]
Hey, thanks for the contribution. I used your code with some modifications.

I made the feature optional, as in some maps that I am using, the marker cluster would be very annoying. So there is a checkbox in the Map Settings now where you can enable it.

The feature is in the source code already, but not on https://facilmap.org/ yet (as there is trouble with the Dockerfile right now). I will install it there soon.

**Comment by pmgouveia** [comment]
yay i made a branch tryin to solve docker stuff  not finished though :/

On 26 de Fevereiro de 2017 16:28:55 CET, Candid Dauth <notifications@github.com> wrote:
>Hey, thanks for the contribution. I used your code with some
>modifications.
>
>I made the feature optional, as in some maps that I am using, the
>marker cluster would be very annoying. So there is a checkbox in the
>Map Settings now where you can enable it.
>
>The feature is in the source code already, but not on
>https://facilmap.org/ yet (as there is trouble with the Dockerfile
>right now). I will install it there soon.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/FacilMap/facilmap2/issues/53#issuecomment-282563616

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cdauth** [comment]
The Dockerfile should be working again.

Note that the file structure has changed quite a lot in the last couple of days, so it might be difficult to merge your changes.

**Comment by cdauth** [comment]
Marker clusters are now available on https://facilmap.org/
