### ISSUE TITLE
points are exported without types

### ISSUE THREAD

**Issue by RM87** [FacilMap/facilmap2#73]
GPX export does not preserve waypoint types.
Both, types and waypoints are exported but there is no connection between those.

Part of gpx export: 

&lt;extensions&gt;
&lt;fm:type name="category 1" type="marker" fields="[]"/&gt;
&lt;fm:type name="category 2" type="marker" fields="[]"/&gt;
&lt;/extensions&gt;
&lt;wpt lat="50.000000" lon="30.000000"&gt;&lt;name&gt;Random point&lt;/name>&lt;desc/&gt;
&lt;extensions&gt;&lt;fm:colour&gt;3166ff&lt;/fm:colour>&lt;/extensions>&lt;/wpt&gt;

**Comment by cdauth** [comment]
The GPX export was originally intended as a way to export all data from a map (including types), but now I chose GeoJSON for this.

My proposal would be to completely remove the fm:type elements from the GPX. Or do you need them for anything?

**Comment by cdauth** [comment]
GPX file now don't contain any FacilMap-specific information anymore.
