### ISSUE TITLE
Deleting saved views does not work

### ISSUE THREAD

**Issue by RM87** [FacilMap/facilmap2#76]
Deleting saved views does not work. 

After confirming the deletion the "bubblecircle" starts spinning and never stops.

**Comment by sznattila** [comment]
Error message after long minutes: The connection to the server was lost.

**Comment by cdauth** [comment]
Happens also in some pads when saving the pad settings. Cannot reproduce locally. The error message indicates that something fails on the server when contacting the mysql server. Hope to find some time to investigate the issue in the next couple of days.

**Comment by cdauth** [comment]
I discovered that when doing any of the actions that cause this problem, the mariadb server starts to leak memory, which eventually causes it to crash. While debugging, it seemed like no unusual amount of queries was sent.

I simply upgraded the mariadb server, and it seems that solved the problem. Could you verify?

**Comment by sznattila** [comment]
Verified. Confirmed :) Deleting and setting Default View is working.
Thank you very much.
