### ISSUE TITLE
Manage views: "Make default" doesn't seem to work.

### ISSUE THREAD

**Issue by sznattila** [FacilMap/facilmap2#77]
Hi.

After confirming the action the "bubblecircle" starts spinning and never stops. 
(acting the same way as https://github.com/FacilMap/facilmap2/issues/76 ?)

**Comment by sznattila** [comment]
Error meesage after long minutes: "connect ECONNREFUSED 172.25.0.3:3306"

**Comment by cdauth** [comment]
Closing as a duplicate of #76
