### ISSUE TITLE
Filter: data.<field> don't seem to work or I am doing something wrong...

### ISSUE THREAD

**Issue by sznattila** [FacilMap/facilmap2#79]
Hi.
Let's assume that I have some custom markers named "LanguageClub".
Let's assume that "LanguageClub" markers have a "Language" field.
Let's assume that some of those fields have the "French" value.
So I use LanguageClub.Language == "French" should show me my French Language Clubs and hides everything else.
What is happening is that everything gets hidden.
What is the proper way to use this filter?

**Comment by cdauth** [comment]
I believe the filter should be `typeId == 123 and data.Language == "French"`. The number `123` needs to be replaced with the number of your type, which is written in the filter dialog in the description of the `typeId` variable.

**Comment by sznattila** [comment]
Tried it now. Same result: Everything gets hidden.

**Comment by cdauth** [comment]
You’re right, the dot notation does not seem to work, see joewalnes/filtrex#12.

I fill implement a fix that flattens the object so that the dot notation will work again.

**Comment by cdauth** [comment]
I deployed the fix to facilmap.org, please test again.

**Comment by sznattila** [comment]
Hi. It seems that it works now :) 
Thank you.

**Comment by sznattila** [comment]
Hi,
There is still one issue I just found: If the field has a "-" (dash), the "data.This-Is-A-Field" format is not working only the "prop" format.

**Comment by cdauth** [comment]
Yes, this is exactly the reason why I made the prop function, because there was no way to use special characters in property names.

**Comment by sznattila** [comment]
Ok... I understand. Thank you for the answer.

**Comment by georg-d** [comment]
There seems to be a regression: In https://facilmap.org/GeorgsTestA#16/47.9755/7.8661 (replace A with RW and W for different access rights) with filter `typeId == 18148 and data.myCheckbox == 1` I see nothing while I see the 1 of the 2 lines (as expected) with filter `typeId == 18148 and prop(data, "myCheckbox") == 1`. I do not know whether it makes more sense in the long run to fix it again or to remove `data.<field>` from documentation.
