### ISSUE TITLE
Http query for lon and lat coordinates...

### ISSUE THREAD

**Issue by sznattila** [FacilMap/facilmap2#81]
Hi,
is there a way to query for long and lat coords via http? 
the idea is this: google sheets =importhtml(url,"table",1) gives me the lat and long in a 1 row 2column table, or importdata(url) gives me a csv list of the coordinates.

Is this possible?

**Comment by cdauth** [comment]
I’m not sure what exactly you want to do. The lat/lon coords of what?

You can get the data of a FacilMap by HTTP as GeoJSON (https://facilmap.org/xyz/geojson) or GPX (https://facilmap.org/xzy/gpx), which are both machine-readable formats (JSON/XML).

**Comment by sznattila** [comment]
Hi,
Sorry for not being clear enough
I want to get the lat/lon coords of an address.
So how do I formulate a http address to facilmap which includes a geographical address to get the coordinates?

**Comment by cdauth** [comment]
FacilMap is itself using an external service, Nominatim (the OpenStreetMap search engine) to resolve addresses. If you want to get coordinates for an address, use Nominatim directly. The documentation is [here](https://wiki.openstreetmap.org/wiki/Nominatim), and example would be http://nominatim.openstreetmap.org/search/Friedrichstr.%20100,%20Berlin?format=json

**Comment by sznattila** [comment]
Thank you.
