### ISSUE TITLE
option to disable or stop accepting inputs?

### ISSUE THREAD

**Issue by govvin** [FacilMap/facilmap2#96]
I couldn't seem to find this option. Is there?

**Comment by cdauth** [comment]
What exactly do you mean by "inputs"?

**Comment by govvin** [comment]
A user can only view the map, not add anything to it.

**Comment by cdauth** [comment]
It's what the read-only link in the map settings is for.

**Comment by govvin** [comment]
Not useful, if you already distributed the link where they can add data

**Comment by cdauth** [comment]
In that case you can change the links and change the read-only link into the one that you shared.
